#!/usr/bin/env tsx
/**
 * intelligent-design setup script
 *
 * Prompts for brand configuration, writes .env.local, and patches
 * the accent color in globals.css. Run once after cloning.
 *
 * Usage: npm run setup
 */

import * as fs from "fs";
import * as path from "path";
import * as readline from "readline";

const ROOT = path.resolve(__dirname, "..");

function ask(rl: readline.Interface, question: string): Promise<string> {
  return new Promise((resolve) => {
    rl.question(question, (answer) => resolve(answer.trim()));
  });
}

async function main() {
  const rl = readline.createInterface({
    input:  process.stdin,
    output: process.stdout,
  });

  console.log("\n🎨  intelligent-design setup\n");
  console.log("Answer the prompts below. Press Enter to accept the default.\n");

  // ── Gather inputs ───────────────────────────────────────────────────────────
  const siteName    = await ask(rl, "Site name (e.g. Acme Inc): ");
  const domain      = await ask(rl, "Domain (e.g. acme.com): ");
  const siteUrl     = `https://${domain}`;
  const contactEmail = await ask(rl, "Contact email (e.g. hello@acme.com): ");

  console.log("\nTheme preset:");
  console.log("  1. dark  — near-black background, light text (product / SaaS)");
  console.log("  2. light — white background, dark text (B2B / corporate)");
  const themeChoice = await ask(rl, "Choose preset [1/2] (default: 1): ") || "1";
  const theme = themeChoice === "2" ? "light" : "dark";

  const accentColor = await ask(rl, "Accent color hex (default: #3B82F6): ") || "#3B82F6";

  const gaId = await ask(rl, "Google Analytics ID (e.g. G-XXXXXXXXXX, leave blank to skip): ");

  const resendKey  = await ask(rl, "Resend API key (leave blank to configure later): ");
  const resendFrom = resendKey
    ? await ask(rl, `From address (e.g. ${siteName} <${contactEmail}>): `) || `${siteName} <${contactEmail}>`
    : "";

  rl.close();

  // ── Write .env.local ────────────────────────────────────────────────────────
  const envPath = path.join(ROOT, ".env.local");
  const envContent = [
    `# Generated by npm run setup on ${new Date().toISOString()}`,
    `NEXT_PUBLIC_SITE_URL=${siteUrl}`,
    `NEXT_PUBLIC_SITE_NAME="${siteName}"`,
    gaId ? `NEXT_PUBLIC_GA_ID=${gaId}` : `# NEXT_PUBLIC_GA_ID=`,
    ``,
    resendKey ? `RESEND_API_KEY=${resendKey}` : `# RESEND_API_KEY=re_xxxx`,
    resendFrom ? `RESEND_FROM="${resendFrom}"` : `# RESEND_FROM="${siteName} <${contactEmail}>"`,
    `CONTACT_FORM_TO=${contactEmail}`,
  ].join("\n");

  fs.writeFileSync(envPath, envContent + "\n");
  console.log("\n✓  .env.local written");

  // ── Patch globals.css — accent color ────────────────────────────────────────
  const cssPath  = path.join(ROOT, "src/app/globals.css");
  let   css      = fs.readFileSync(cssPath, "utf8");

  // Replace both accent and accent-hover (darken by ~10% for hover)
  css = css.replace(/--color-accent:\s+#[0-9A-Fa-f]{3,8};/, `--color-accent:       ${accentColor};`);
  // Simple hover: same color (user can refine manually)
  css = css.replace(/--color-accent-hover:\s+#[0-9A-Fa-f]{3,8};/, `--color-accent-hover: ${accentColor};`);

  // ── Patch globals.css — theme preset ────────────────────────────────────────
  if (theme === "light") {
    // Comment out dark preset, uncomment light preset
    css = css.replace("/* ── Light preset — uncomment and remove dark preset above to activate ───────", "/* ── Dark preset — swap with light preset below to re-activate ─────────────");
    css = css.replace("── */", "── */\n\n/* ── Light preset (active) ──────────────────────────────────────────────────");
    console.log("✓  Light theme preset activated");
  }

  fs.writeFileSync(cssPath, css);
  console.log(`✓  Accent color set to ${accentColor}`);

  // ── Update site.ts with site name + domain ──────────────────────────────────
  const siteTsPath = path.join(ROOT, "src/content/site.ts");
  let   siteTs     = fs.readFileSync(siteTsPath, "utf8");

  siteTs = siteTs.replace(/name:\s+"Your Site"/, `name:        "${siteName}"`);
  siteTs = siteTs.replace(/domain:\s+"yoursite\.com"/, `domain:      "${domain}"`);
  siteTs = siteTs.replace(/url:\s+"https:\/\/yoursite\.com"/, `url:         "${siteUrl}"`);
  siteTs = siteTs.replace(/email:\s+"hello@yoursite\.com"/, `email:   "${contactEmail}"`);

  fs.writeFileSync(siteTsPath, siteTs);
  console.log("✓  src/content/site.ts updated");

  // ── Done ────────────────────────────────────────────────────────────────────
  console.log(`
✅  Setup complete!

Next steps:
  1. Update src/content/site.ts — add your nav links, footer columns, tagline
  2. Update src/content/homepage.ts — add your real hero copy, features, FAQs
  3. Add your logo to public/images/ and reference it in src/components/layout/header.tsx
  4. Fill in public/llms.txt and public/llms-full.txt
  5. Replace public/og-image.png with a real 1200×630 image
  6. npm run dev — preview at http://localhost:3000
  7. When ready: npx vercel deploy
`);
}

main().catch((err) => {
  console.error("Setup failed:", err);
  process.exit(1);
});
